# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170731_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashO', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='itemType',
            field=models.CharField(choices=[('Academic Use', 'Academic Use'), ('Office Use', 'Office Use')], default='Academic Use', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemBuy', to='home.Item'),
        ),
        migrations.AddField(
            model_name='offer',
            name='itemO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemOffer', to='home.Item'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.User'),
        ),
    ]
